/* eslint-disable */
/*Proudly generated by GenDocu.com*/
// package: lnrpc
// file: rpc.proto

import * as rpc_pb from "./rpc_pb";
import {grpc} from "@improbable-eng/grpc-web";

type LightningWalletBalance = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.WalletBalanceRequest;
  readonly responseType: typeof rpc_pb.WalletBalanceResponse;
};

type LightningChannelBalance = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ChannelBalanceRequest;
  readonly responseType: typeof rpc_pb.ChannelBalanceResponse;
};

type LightningGetTransactions = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.GetTransactionsRequest;
  readonly responseType: typeof rpc_pb.TransactionDetails;
};

type LightningEstimateFee = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.EstimateFeeRequest;
  readonly responseType: typeof rpc_pb.EstimateFeeResponse;
};

type LightningSendCoins = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.SendCoinsRequest;
  readonly responseType: typeof rpc_pb.SendCoinsResponse;
};

type LightningListUnspent = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ListUnspentRequest;
  readonly responseType: typeof rpc_pb.ListUnspentResponse;
};

type LightningSubscribeTransactions = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: true;
  readonly requestType: typeof rpc_pb.GetTransactionsRequest;
  readonly responseType: typeof rpc_pb.Transaction;
};

type LightningSendMany = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.SendManyRequest;
  readonly responseType: typeof rpc_pb.SendManyResponse;
};

type LightningNewAddress = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.NewAddressRequest;
  readonly responseType: typeof rpc_pb.NewAddressResponse;
};

type LightningSignMessage = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.SignMessageRequest;
  readonly responseType: typeof rpc_pb.SignMessageResponse;
};

type LightningVerifyMessage = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.VerifyMessageRequest;
  readonly responseType: typeof rpc_pb.VerifyMessageResponse;
};

type LightningConnectPeer = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ConnectPeerRequest;
  readonly responseType: typeof rpc_pb.ConnectPeerResponse;
};

type LightningDisconnectPeer = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.DisconnectPeerRequest;
  readonly responseType: typeof rpc_pb.DisconnectPeerResponse;
};

type LightningListPeers = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ListPeersRequest;
  readonly responseType: typeof rpc_pb.ListPeersResponse;
};

type LightningSubscribePeerEvents = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: true;
  readonly requestType: typeof rpc_pb.PeerEventSubscription;
  readonly responseType: typeof rpc_pb.PeerEvent;
};

type LightningGetInfo = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.GetInfoRequest;
  readonly responseType: typeof rpc_pb.GetInfoResponse;
};

type LightningGetRecoveryInfo = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.GetRecoveryInfoRequest;
  readonly responseType: typeof rpc_pb.GetRecoveryInfoResponse;
};

type LightningPendingChannels = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.PendingChannelsRequest;
  readonly responseType: typeof rpc_pb.PendingChannelsResponse;
};

type LightningListChannels = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ListChannelsRequest;
  readonly responseType: typeof rpc_pb.ListChannelsResponse;
};

type LightningSubscribeChannelEvents = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: true;
  readonly requestType: typeof rpc_pb.ChannelEventSubscription;
  readonly responseType: typeof rpc_pb.ChannelEventUpdate;
};

type LightningClosedChannels = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ClosedChannelsRequest;
  readonly responseType: typeof rpc_pb.ClosedChannelsResponse;
};

type LightningOpenChannelSync = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.OpenChannelRequest;
  readonly responseType: typeof rpc_pb.ChannelPoint;
};

type LightningOpenChannel = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: true;
  readonly requestType: typeof rpc_pb.OpenChannelRequest;
  readonly responseType: typeof rpc_pb.OpenStatusUpdate;
};

type LightningFundingStateStep = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.FundingTransitionMsg;
  readonly responseType: typeof rpc_pb.FundingStateStepResp;
};

type LightningChannelAcceptor = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: true;
  readonly responseStream: true;
  readonly requestType: typeof rpc_pb.ChannelAcceptResponse;
  readonly responseType: typeof rpc_pb.ChannelAcceptRequest;
};

type LightningCloseChannel = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: true;
  readonly requestType: typeof rpc_pb.CloseChannelRequest;
  readonly responseType: typeof rpc_pb.CloseStatusUpdate;
};

type LightningAbandonChannel = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.AbandonChannelRequest;
  readonly responseType: typeof rpc_pb.AbandonChannelResponse;
};

type LightningSendPayment = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: true;
  readonly responseStream: true;
  readonly requestType: typeof rpc_pb.SendRequest;
  readonly responseType: typeof rpc_pb.SendResponse;
};

type LightningSendPaymentSync = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.SendRequest;
  readonly responseType: typeof rpc_pb.SendResponse;
};

type LightningSendToRoute = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: true;
  readonly responseStream: true;
  readonly requestType: typeof rpc_pb.SendToRouteRequest;
  readonly responseType: typeof rpc_pb.SendResponse;
};

type LightningSendToRouteSync = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.SendToRouteRequest;
  readonly responseType: typeof rpc_pb.SendResponse;
};

type LightningAddInvoice = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.Invoice;
  readonly responseType: typeof rpc_pb.AddInvoiceResponse;
};

type LightningListInvoices = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ListInvoiceRequest;
  readonly responseType: typeof rpc_pb.ListInvoiceResponse;
};

type LightningLookupInvoice = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.PaymentHash;
  readonly responseType: typeof rpc_pb.Invoice;
};

type LightningSubscribeInvoices = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: true;
  readonly requestType: typeof rpc_pb.InvoiceSubscription;
  readonly responseType: typeof rpc_pb.Invoice;
};

type LightningDecodePayReq = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.PayReqString;
  readonly responseType: typeof rpc_pb.PayReq;
};

type LightningListPayments = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ListPaymentsRequest;
  readonly responseType: typeof rpc_pb.ListPaymentsResponse;
};

type LightningDeleteAllPayments = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.DeleteAllPaymentsRequest;
  readonly responseType: typeof rpc_pb.DeleteAllPaymentsResponse;
};

type LightningDescribeGraph = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ChannelGraphRequest;
  readonly responseType: typeof rpc_pb.ChannelGraph;
};

type LightningGetNodeMetrics = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.NodeMetricsRequest;
  readonly responseType: typeof rpc_pb.NodeMetricsResponse;
};

type LightningGetChanInfo = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ChanInfoRequest;
  readonly responseType: typeof rpc_pb.ChannelEdge;
};

type LightningGetNodeInfo = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.NodeInfoRequest;
  readonly responseType: typeof rpc_pb.NodeInfo;
};

type LightningQueryRoutes = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.QueryRoutesRequest;
  readonly responseType: typeof rpc_pb.QueryRoutesResponse;
};

type LightningGetNetworkInfo = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.NetworkInfoRequest;
  readonly responseType: typeof rpc_pb.NetworkInfo;
};

type LightningStopDaemon = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.StopRequest;
  readonly responseType: typeof rpc_pb.StopResponse;
};

type LightningSubscribeChannelGraph = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: true;
  readonly requestType: typeof rpc_pb.GraphTopologySubscription;
  readonly responseType: typeof rpc_pb.GraphTopologyUpdate;
};

type LightningDebugLevel = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.DebugLevelRequest;
  readonly responseType: typeof rpc_pb.DebugLevelResponse;
};

type LightningFeeReport = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.FeeReportRequest;
  readonly responseType: typeof rpc_pb.FeeReportResponse;
};

type LightningUpdateChannelPolicy = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.PolicyUpdateRequest;
  readonly responseType: typeof rpc_pb.PolicyUpdateResponse;
};

type LightningForwardingHistory = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ForwardingHistoryRequest;
  readonly responseType: typeof rpc_pb.ForwardingHistoryResponse;
};

type LightningExportChannelBackup = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ExportChannelBackupRequest;
  readonly responseType: typeof rpc_pb.ChannelBackup;
};

type LightningExportAllChannelBackups = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ChanBackupExportRequest;
  readonly responseType: typeof rpc_pb.ChanBackupSnapshot;
};

type LightningVerifyChanBackup = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ChanBackupSnapshot;
  readonly responseType: typeof rpc_pb.VerifyChanBackupResponse;
};

type LightningRestoreChannelBackups = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.RestoreChanBackupRequest;
  readonly responseType: typeof rpc_pb.RestoreBackupResponse;
};

type LightningSubscribeChannelBackups = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: true;
  readonly requestType: typeof rpc_pb.ChannelBackupSubscription;
  readonly responseType: typeof rpc_pb.ChanBackupSnapshot;
};

type LightningBakeMacaroon = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.BakeMacaroonRequest;
  readonly responseType: typeof rpc_pb.BakeMacaroonResponse;
};

type LightningListMacaroonIDs = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ListMacaroonIDsRequest;
  readonly responseType: typeof rpc_pb.ListMacaroonIDsResponse;
};

type LightningDeleteMacaroonID = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.DeleteMacaroonIDRequest;
  readonly responseType: typeof rpc_pb.DeleteMacaroonIDResponse;
};

type LightningListPermissions = {
  readonly methodName: string;
  readonly service: typeof Lightning;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof rpc_pb.ListPermissionsRequest;
  readonly responseType: typeof rpc_pb.ListPermissionsResponse;
};

export class Lightning {
  static readonly serviceName: string;
  static readonly WalletBalance: LightningWalletBalance;
  static readonly ChannelBalance: LightningChannelBalance;
  static readonly GetTransactions: LightningGetTransactions;
  static readonly EstimateFee: LightningEstimateFee;
  static readonly SendCoins: LightningSendCoins;
  static readonly ListUnspent: LightningListUnspent;
  static readonly SubscribeTransactions: LightningSubscribeTransactions;
  static readonly SendMany: LightningSendMany;
  static readonly NewAddress: LightningNewAddress;
  static readonly SignMessage: LightningSignMessage;
  static readonly VerifyMessage: LightningVerifyMessage;
  static readonly ConnectPeer: LightningConnectPeer;
  static readonly DisconnectPeer: LightningDisconnectPeer;
  static readonly ListPeers: LightningListPeers;
  static readonly SubscribePeerEvents: LightningSubscribePeerEvents;
  static readonly GetInfo: LightningGetInfo;
  static readonly GetRecoveryInfo: LightningGetRecoveryInfo;
  static readonly PendingChannels: LightningPendingChannels;
  static readonly ListChannels: LightningListChannels;
  static readonly SubscribeChannelEvents: LightningSubscribeChannelEvents;
  static readonly ClosedChannels: LightningClosedChannels;
  static readonly OpenChannelSync: LightningOpenChannelSync;
  static readonly OpenChannel: LightningOpenChannel;
  static readonly FundingStateStep: LightningFundingStateStep;
  static readonly ChannelAcceptor: LightningChannelAcceptor;
  static readonly CloseChannel: LightningCloseChannel;
  static readonly AbandonChannel: LightningAbandonChannel;
  static readonly SendPayment: LightningSendPayment;
  static readonly SendPaymentSync: LightningSendPaymentSync;
  static readonly SendToRoute: LightningSendToRoute;
  static readonly SendToRouteSync: LightningSendToRouteSync;
  static readonly AddInvoice: LightningAddInvoice;
  static readonly ListInvoices: LightningListInvoices;
  static readonly LookupInvoice: LightningLookupInvoice;
  static readonly SubscribeInvoices: LightningSubscribeInvoices;
  static readonly DecodePayReq: LightningDecodePayReq;
  static readonly ListPayments: LightningListPayments;
  static readonly DeleteAllPayments: LightningDeleteAllPayments;
  static readonly DescribeGraph: LightningDescribeGraph;
  static readonly GetNodeMetrics: LightningGetNodeMetrics;
  static readonly GetChanInfo: LightningGetChanInfo;
  static readonly GetNodeInfo: LightningGetNodeInfo;
  static readonly QueryRoutes: LightningQueryRoutes;
  static readonly GetNetworkInfo: LightningGetNetworkInfo;
  static readonly StopDaemon: LightningStopDaemon;
  static readonly SubscribeChannelGraph: LightningSubscribeChannelGraph;
  static readonly DebugLevel: LightningDebugLevel;
  static readonly FeeReport: LightningFeeReport;
  static readonly UpdateChannelPolicy: LightningUpdateChannelPolicy;
  static readonly ForwardingHistory: LightningForwardingHistory;
  static readonly ExportChannelBackup: LightningExportChannelBackup;
  static readonly ExportAllChannelBackups: LightningExportAllChannelBackups;
  static readonly VerifyChanBackup: LightningVerifyChanBackup;
  static readonly RestoreChannelBackups: LightningRestoreChannelBackups;
  static readonly SubscribeChannelBackups: LightningSubscribeChannelBackups;
  static readonly BakeMacaroon: LightningBakeMacaroon;
  static readonly ListMacaroonIDs: LightningListMacaroonIDs;
  static readonly DeleteMacaroonID: LightningDeleteMacaroonID;
  static readonly ListPermissions: LightningListPermissions;
}

export type ServiceError = { message: string, code: number; metadata: grpc.Metadata }
export type Status = { details: string, code: number; metadata: grpc.Metadata }

interface UnaryResponse {
  cancel(): void;
}
interface ResponseStream<T> {
  cancel(): void;
  on(type: 'data', handler: (message: T) => void): ResponseStream<T>;
  on(type: 'end', handler: (status?: Status) => void): ResponseStream<T>;
  on(type: 'status', handler: (status: Status) => void): ResponseStream<T>;
}
interface RequestStream<T> {
  write(message: T): RequestStream<T>;
  end(): void;
  cancel(): void;
  on(type: 'end', handler: (status?: Status) => void): RequestStream<T>;
  on(type: 'status', handler: (status: Status) => void): RequestStream<T>;
}
interface BidirectionalStream<ReqT, ResT> {
  write(message: ReqT): BidirectionalStream<ReqT, ResT>;
  end(): void;
  cancel(): void;
  on(type: 'data', handler: (message: ResT) => void): BidirectionalStream<ReqT, ResT>;
  on(type: 'end', handler: (status?: Status) => void): BidirectionalStream<ReqT, ResT>;
  on(type: 'status', handler: (status: Status) => void): BidirectionalStream<ReqT, ResT>;
}

export class LightningClient {
  readonly serviceHost: string;

  constructor(serviceHost: string, options?: grpc.RpcOptions);
  walletBalance(
    requestMessage: rpc_pb.WalletBalanceRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.WalletBalanceResponse|null) => void
  ): UnaryResponse;
  walletBalance(
    requestMessage: rpc_pb.WalletBalanceRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.WalletBalanceResponse|null) => void
  ): UnaryResponse;
  channelBalance(
    requestMessage: rpc_pb.ChannelBalanceRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ChannelBalanceResponse|null) => void
  ): UnaryResponse;
  channelBalance(
    requestMessage: rpc_pb.ChannelBalanceRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ChannelBalanceResponse|null) => void
  ): UnaryResponse;
  getTransactions(
    requestMessage: rpc_pb.GetTransactionsRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.TransactionDetails|null) => void
  ): UnaryResponse;
  getTransactions(
    requestMessage: rpc_pb.GetTransactionsRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.TransactionDetails|null) => void
  ): UnaryResponse;
  estimateFee(
    requestMessage: rpc_pb.EstimateFeeRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.EstimateFeeResponse|null) => void
  ): UnaryResponse;
  estimateFee(
    requestMessage: rpc_pb.EstimateFeeRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.EstimateFeeResponse|null) => void
  ): UnaryResponse;
  sendCoins(
    requestMessage: rpc_pb.SendCoinsRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.SendCoinsResponse|null) => void
  ): UnaryResponse;
  sendCoins(
    requestMessage: rpc_pb.SendCoinsRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.SendCoinsResponse|null) => void
  ): UnaryResponse;
  listUnspent(
    requestMessage: rpc_pb.ListUnspentRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListUnspentResponse|null) => void
  ): UnaryResponse;
  listUnspent(
    requestMessage: rpc_pb.ListUnspentRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListUnspentResponse|null) => void
  ): UnaryResponse;
  subscribeTransactions(requestMessage: rpc_pb.GetTransactionsRequest, metadata?: grpc.Metadata): ResponseStream<rpc_pb.Transaction>;
  sendMany(
    requestMessage: rpc_pb.SendManyRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.SendManyResponse|null) => void
  ): UnaryResponse;
  sendMany(
    requestMessage: rpc_pb.SendManyRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.SendManyResponse|null) => void
  ): UnaryResponse;
  newAddress(
    requestMessage: rpc_pb.NewAddressRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.NewAddressResponse|null) => void
  ): UnaryResponse;
  newAddress(
    requestMessage: rpc_pb.NewAddressRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.NewAddressResponse|null) => void
  ): UnaryResponse;
  signMessage(
    requestMessage: rpc_pb.SignMessageRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.SignMessageResponse|null) => void
  ): UnaryResponse;
  signMessage(
    requestMessage: rpc_pb.SignMessageRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.SignMessageResponse|null) => void
  ): UnaryResponse;
  verifyMessage(
    requestMessage: rpc_pb.VerifyMessageRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.VerifyMessageResponse|null) => void
  ): UnaryResponse;
  verifyMessage(
    requestMessage: rpc_pb.VerifyMessageRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.VerifyMessageResponse|null) => void
  ): UnaryResponse;
  connectPeer(
    requestMessage: rpc_pb.ConnectPeerRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ConnectPeerResponse|null) => void
  ): UnaryResponse;
  connectPeer(
    requestMessage: rpc_pb.ConnectPeerRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ConnectPeerResponse|null) => void
  ): UnaryResponse;
  disconnectPeer(
    requestMessage: rpc_pb.DisconnectPeerRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.DisconnectPeerResponse|null) => void
  ): UnaryResponse;
  disconnectPeer(
    requestMessage: rpc_pb.DisconnectPeerRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.DisconnectPeerResponse|null) => void
  ): UnaryResponse;
  listPeers(
    requestMessage: rpc_pb.ListPeersRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListPeersResponse|null) => void
  ): UnaryResponse;
  listPeers(
    requestMessage: rpc_pb.ListPeersRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListPeersResponse|null) => void
  ): UnaryResponse;
  subscribePeerEvents(requestMessage: rpc_pb.PeerEventSubscription, metadata?: grpc.Metadata): ResponseStream<rpc_pb.PeerEvent>;
  getInfo(
    requestMessage: rpc_pb.GetInfoRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.GetInfoResponse|null) => void
  ): UnaryResponse;
  getInfo(
    requestMessage: rpc_pb.GetInfoRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.GetInfoResponse|null) => void
  ): UnaryResponse;
  getRecoveryInfo(
    requestMessage: rpc_pb.GetRecoveryInfoRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.GetRecoveryInfoResponse|null) => void
  ): UnaryResponse;
  getRecoveryInfo(
    requestMessage: rpc_pb.GetRecoveryInfoRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.GetRecoveryInfoResponse|null) => void
  ): UnaryResponse;
  pendingChannels(
    requestMessage: rpc_pb.PendingChannelsRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.PendingChannelsResponse|null) => void
  ): UnaryResponse;
  pendingChannels(
    requestMessage: rpc_pb.PendingChannelsRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.PendingChannelsResponse|null) => void
  ): UnaryResponse;
  listChannels(
    requestMessage: rpc_pb.ListChannelsRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListChannelsResponse|null) => void
  ): UnaryResponse;
  listChannels(
    requestMessage: rpc_pb.ListChannelsRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListChannelsResponse|null) => void
  ): UnaryResponse;
  subscribeChannelEvents(requestMessage: rpc_pb.ChannelEventSubscription, metadata?: grpc.Metadata): ResponseStream<rpc_pb.ChannelEventUpdate>;
  closedChannels(
    requestMessage: rpc_pb.ClosedChannelsRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ClosedChannelsResponse|null) => void
  ): UnaryResponse;
  closedChannels(
    requestMessage: rpc_pb.ClosedChannelsRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ClosedChannelsResponse|null) => void
  ): UnaryResponse;
  openChannelSync(
    requestMessage: rpc_pb.OpenChannelRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ChannelPoint|null) => void
  ): UnaryResponse;
  openChannelSync(
    requestMessage: rpc_pb.OpenChannelRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ChannelPoint|null) => void
  ): UnaryResponse;
  openChannel(requestMessage: rpc_pb.OpenChannelRequest, metadata?: grpc.Metadata): ResponseStream<rpc_pb.OpenStatusUpdate>;
  fundingStateStep(
    requestMessage: rpc_pb.FundingTransitionMsg,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.FundingStateStepResp|null) => void
  ): UnaryResponse;
  fundingStateStep(
    requestMessage: rpc_pb.FundingTransitionMsg,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.FundingStateStepResp|null) => void
  ): UnaryResponse;
  channelAcceptor(metadata?: grpc.Metadata): BidirectionalStream<rpc_pb.ChannelAcceptResponse, rpc_pb.ChannelAcceptRequest>;
  closeChannel(requestMessage: rpc_pb.CloseChannelRequest, metadata?: grpc.Metadata): ResponseStream<rpc_pb.CloseStatusUpdate>;
  abandonChannel(
    requestMessage: rpc_pb.AbandonChannelRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.AbandonChannelResponse|null) => void
  ): UnaryResponse;
  abandonChannel(
    requestMessage: rpc_pb.AbandonChannelRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.AbandonChannelResponse|null) => void
  ): UnaryResponse;
  sendPayment(metadata?: grpc.Metadata): BidirectionalStream<rpc_pb.SendRequest, rpc_pb.SendResponse>;
  sendPaymentSync(
    requestMessage: rpc_pb.SendRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.SendResponse|null) => void
  ): UnaryResponse;
  sendPaymentSync(
    requestMessage: rpc_pb.SendRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.SendResponse|null) => void
  ): UnaryResponse;
  sendToRoute(metadata?: grpc.Metadata): BidirectionalStream<rpc_pb.SendToRouteRequest, rpc_pb.SendResponse>;
  sendToRouteSync(
    requestMessage: rpc_pb.SendToRouteRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.SendResponse|null) => void
  ): UnaryResponse;
  sendToRouteSync(
    requestMessage: rpc_pb.SendToRouteRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.SendResponse|null) => void
  ): UnaryResponse;
  addInvoice(
    requestMessage: rpc_pb.Invoice,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.AddInvoiceResponse|null) => void
  ): UnaryResponse;
  addInvoice(
    requestMessage: rpc_pb.Invoice,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.AddInvoiceResponse|null) => void
  ): UnaryResponse;
  listInvoices(
    requestMessage: rpc_pb.ListInvoiceRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListInvoiceResponse|null) => void
  ): UnaryResponse;
  listInvoices(
    requestMessage: rpc_pb.ListInvoiceRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListInvoiceResponse|null) => void
  ): UnaryResponse;
  lookupInvoice(
    requestMessage: rpc_pb.PaymentHash,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.Invoice|null) => void
  ): UnaryResponse;
  lookupInvoice(
    requestMessage: rpc_pb.PaymentHash,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.Invoice|null) => void
  ): UnaryResponse;
  subscribeInvoices(requestMessage: rpc_pb.InvoiceSubscription, metadata?: grpc.Metadata): ResponseStream<rpc_pb.Invoice>;
  decodePayReq(
    requestMessage: rpc_pb.PayReqString,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.PayReq|null) => void
  ): UnaryResponse;
  decodePayReq(
    requestMessage: rpc_pb.PayReqString,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.PayReq|null) => void
  ): UnaryResponse;
  listPayments(
    requestMessage: rpc_pb.ListPaymentsRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListPaymentsResponse|null) => void
  ): UnaryResponse;
  listPayments(
    requestMessage: rpc_pb.ListPaymentsRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListPaymentsResponse|null) => void
  ): UnaryResponse;
  deleteAllPayments(
    requestMessage: rpc_pb.DeleteAllPaymentsRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.DeleteAllPaymentsResponse|null) => void
  ): UnaryResponse;
  deleteAllPayments(
    requestMessage: rpc_pb.DeleteAllPaymentsRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.DeleteAllPaymentsResponse|null) => void
  ): UnaryResponse;
  describeGraph(
    requestMessage: rpc_pb.ChannelGraphRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ChannelGraph|null) => void
  ): UnaryResponse;
  describeGraph(
    requestMessage: rpc_pb.ChannelGraphRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ChannelGraph|null) => void
  ): UnaryResponse;
  getNodeMetrics(
    requestMessage: rpc_pb.NodeMetricsRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.NodeMetricsResponse|null) => void
  ): UnaryResponse;
  getNodeMetrics(
    requestMessage: rpc_pb.NodeMetricsRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.NodeMetricsResponse|null) => void
  ): UnaryResponse;
  getChanInfo(
    requestMessage: rpc_pb.ChanInfoRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ChannelEdge|null) => void
  ): UnaryResponse;
  getChanInfo(
    requestMessage: rpc_pb.ChanInfoRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ChannelEdge|null) => void
  ): UnaryResponse;
  getNodeInfo(
    requestMessage: rpc_pb.NodeInfoRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.NodeInfo|null) => void
  ): UnaryResponse;
  getNodeInfo(
    requestMessage: rpc_pb.NodeInfoRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.NodeInfo|null) => void
  ): UnaryResponse;
  queryRoutes(
    requestMessage: rpc_pb.QueryRoutesRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.QueryRoutesResponse|null) => void
  ): UnaryResponse;
  queryRoutes(
    requestMessage: rpc_pb.QueryRoutesRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.QueryRoutesResponse|null) => void
  ): UnaryResponse;
  getNetworkInfo(
    requestMessage: rpc_pb.NetworkInfoRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.NetworkInfo|null) => void
  ): UnaryResponse;
  getNetworkInfo(
    requestMessage: rpc_pb.NetworkInfoRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.NetworkInfo|null) => void
  ): UnaryResponse;
  stopDaemon(
    requestMessage: rpc_pb.StopRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.StopResponse|null) => void
  ): UnaryResponse;
  stopDaemon(
    requestMessage: rpc_pb.StopRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.StopResponse|null) => void
  ): UnaryResponse;
  subscribeChannelGraph(requestMessage: rpc_pb.GraphTopologySubscription, metadata?: grpc.Metadata): ResponseStream<rpc_pb.GraphTopologyUpdate>;
  debugLevel(
    requestMessage: rpc_pb.DebugLevelRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.DebugLevelResponse|null) => void
  ): UnaryResponse;
  debugLevel(
    requestMessage: rpc_pb.DebugLevelRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.DebugLevelResponse|null) => void
  ): UnaryResponse;
  feeReport(
    requestMessage: rpc_pb.FeeReportRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.FeeReportResponse|null) => void
  ): UnaryResponse;
  feeReport(
    requestMessage: rpc_pb.FeeReportRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.FeeReportResponse|null) => void
  ): UnaryResponse;
  updateChannelPolicy(
    requestMessage: rpc_pb.PolicyUpdateRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.PolicyUpdateResponse|null) => void
  ): UnaryResponse;
  updateChannelPolicy(
    requestMessage: rpc_pb.PolicyUpdateRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.PolicyUpdateResponse|null) => void
  ): UnaryResponse;
  forwardingHistory(
    requestMessage: rpc_pb.ForwardingHistoryRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ForwardingHistoryResponse|null) => void
  ): UnaryResponse;
  forwardingHistory(
    requestMessage: rpc_pb.ForwardingHistoryRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ForwardingHistoryResponse|null) => void
  ): UnaryResponse;
  exportChannelBackup(
    requestMessage: rpc_pb.ExportChannelBackupRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ChannelBackup|null) => void
  ): UnaryResponse;
  exportChannelBackup(
    requestMessage: rpc_pb.ExportChannelBackupRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ChannelBackup|null) => void
  ): UnaryResponse;
  exportAllChannelBackups(
    requestMessage: rpc_pb.ChanBackupExportRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ChanBackupSnapshot|null) => void
  ): UnaryResponse;
  exportAllChannelBackups(
    requestMessage: rpc_pb.ChanBackupExportRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ChanBackupSnapshot|null) => void
  ): UnaryResponse;
  verifyChanBackup(
    requestMessage: rpc_pb.ChanBackupSnapshot,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.VerifyChanBackupResponse|null) => void
  ): UnaryResponse;
  verifyChanBackup(
    requestMessage: rpc_pb.ChanBackupSnapshot,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.VerifyChanBackupResponse|null) => void
  ): UnaryResponse;
  restoreChannelBackups(
    requestMessage: rpc_pb.RestoreChanBackupRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.RestoreBackupResponse|null) => void
  ): UnaryResponse;
  restoreChannelBackups(
    requestMessage: rpc_pb.RestoreChanBackupRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.RestoreBackupResponse|null) => void
  ): UnaryResponse;
  subscribeChannelBackups(requestMessage: rpc_pb.ChannelBackupSubscription, metadata?: grpc.Metadata): ResponseStream<rpc_pb.ChanBackupSnapshot>;
  bakeMacaroon(
    requestMessage: rpc_pb.BakeMacaroonRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.BakeMacaroonResponse|null) => void
  ): UnaryResponse;
  bakeMacaroon(
    requestMessage: rpc_pb.BakeMacaroonRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.BakeMacaroonResponse|null) => void
  ): UnaryResponse;
  listMacaroonIDs(
    requestMessage: rpc_pb.ListMacaroonIDsRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListMacaroonIDsResponse|null) => void
  ): UnaryResponse;
  listMacaroonIDs(
    requestMessage: rpc_pb.ListMacaroonIDsRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListMacaroonIDsResponse|null) => void
  ): UnaryResponse;
  deleteMacaroonID(
    requestMessage: rpc_pb.DeleteMacaroonIDRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.DeleteMacaroonIDResponse|null) => void
  ): UnaryResponse;
  deleteMacaroonID(
    requestMessage: rpc_pb.DeleteMacaroonIDRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.DeleteMacaroonIDResponse|null) => void
  ): UnaryResponse;
  listPermissions(
    requestMessage: rpc_pb.ListPermissionsRequest,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListPermissionsResponse|null) => void
  ): UnaryResponse;
  listPermissions(
    requestMessage: rpc_pb.ListPermissionsRequest,
    callback: (error: ServiceError|null, responseMessage: rpc_pb.ListPermissionsResponse|null) => void
  ): UnaryResponse;
}

