/* eslint-disable */
/*Proudly generated by GenDocu.com*/
// package: lnrpc
// file: rpc.proto

var rpc_pb = require("./rpc_pb");
var grpc = require("@improbable-eng/grpc-web").grpc;

var Lightning = (function () {
  function Lightning() {}
  Lightning.serviceName = "lnrpc.Lightning";
  return Lightning;
}());

Lightning.WalletBalance = {
  methodName: "WalletBalance",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.WalletBalanceRequest,
  responseType: rpc_pb.WalletBalanceResponse
};

Lightning.ChannelBalance = {
  methodName: "ChannelBalance",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ChannelBalanceRequest,
  responseType: rpc_pb.ChannelBalanceResponse
};

Lightning.GetTransactions = {
  methodName: "GetTransactions",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.GetTransactionsRequest,
  responseType: rpc_pb.TransactionDetails
};

Lightning.EstimateFee = {
  methodName: "EstimateFee",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.EstimateFeeRequest,
  responseType: rpc_pb.EstimateFeeResponse
};

Lightning.SendCoins = {
  methodName: "SendCoins",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.SendCoinsRequest,
  responseType: rpc_pb.SendCoinsResponse
};

Lightning.ListUnspent = {
  methodName: "ListUnspent",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ListUnspentRequest,
  responseType: rpc_pb.ListUnspentResponse
};

Lightning.SubscribeTransactions = {
  methodName: "SubscribeTransactions",
  service: Lightning,
  requestStream: false,
  responseStream: true,
  requestType: rpc_pb.GetTransactionsRequest,
  responseType: rpc_pb.Transaction
};

Lightning.SendMany = {
  methodName: "SendMany",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.SendManyRequest,
  responseType: rpc_pb.SendManyResponse
};

Lightning.NewAddress = {
  methodName: "NewAddress",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.NewAddressRequest,
  responseType: rpc_pb.NewAddressResponse
};

Lightning.SignMessage = {
  methodName: "SignMessage",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.SignMessageRequest,
  responseType: rpc_pb.SignMessageResponse
};

Lightning.VerifyMessage = {
  methodName: "VerifyMessage",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.VerifyMessageRequest,
  responseType: rpc_pb.VerifyMessageResponse
};

Lightning.ConnectPeer = {
  methodName: "ConnectPeer",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ConnectPeerRequest,
  responseType: rpc_pb.ConnectPeerResponse
};

Lightning.DisconnectPeer = {
  methodName: "DisconnectPeer",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.DisconnectPeerRequest,
  responseType: rpc_pb.DisconnectPeerResponse
};

Lightning.ListPeers = {
  methodName: "ListPeers",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ListPeersRequest,
  responseType: rpc_pb.ListPeersResponse
};

Lightning.SubscribePeerEvents = {
  methodName: "SubscribePeerEvents",
  service: Lightning,
  requestStream: false,
  responseStream: true,
  requestType: rpc_pb.PeerEventSubscription,
  responseType: rpc_pb.PeerEvent
};

Lightning.GetInfo = {
  methodName: "GetInfo",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.GetInfoRequest,
  responseType: rpc_pb.GetInfoResponse
};

Lightning.GetRecoveryInfo = {
  methodName: "GetRecoveryInfo",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.GetRecoveryInfoRequest,
  responseType: rpc_pb.GetRecoveryInfoResponse
};

Lightning.PendingChannels = {
  methodName: "PendingChannels",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.PendingChannelsRequest,
  responseType: rpc_pb.PendingChannelsResponse
};

Lightning.ListChannels = {
  methodName: "ListChannels",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ListChannelsRequest,
  responseType: rpc_pb.ListChannelsResponse
};

Lightning.SubscribeChannelEvents = {
  methodName: "SubscribeChannelEvents",
  service: Lightning,
  requestStream: false,
  responseStream: true,
  requestType: rpc_pb.ChannelEventSubscription,
  responseType: rpc_pb.ChannelEventUpdate
};

Lightning.ClosedChannels = {
  methodName: "ClosedChannels",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ClosedChannelsRequest,
  responseType: rpc_pb.ClosedChannelsResponse
};

Lightning.OpenChannelSync = {
  methodName: "OpenChannelSync",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.OpenChannelRequest,
  responseType: rpc_pb.ChannelPoint
};

Lightning.OpenChannel = {
  methodName: "OpenChannel",
  service: Lightning,
  requestStream: false,
  responseStream: true,
  requestType: rpc_pb.OpenChannelRequest,
  responseType: rpc_pb.OpenStatusUpdate
};

Lightning.FundingStateStep = {
  methodName: "FundingStateStep",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.FundingTransitionMsg,
  responseType: rpc_pb.FundingStateStepResp
};

Lightning.ChannelAcceptor = {
  methodName: "ChannelAcceptor",
  service: Lightning,
  requestStream: true,
  responseStream: true,
  requestType: rpc_pb.ChannelAcceptResponse,
  responseType: rpc_pb.ChannelAcceptRequest
};

Lightning.CloseChannel = {
  methodName: "CloseChannel",
  service: Lightning,
  requestStream: false,
  responseStream: true,
  requestType: rpc_pb.CloseChannelRequest,
  responseType: rpc_pb.CloseStatusUpdate
};

Lightning.AbandonChannel = {
  methodName: "AbandonChannel",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.AbandonChannelRequest,
  responseType: rpc_pb.AbandonChannelResponse
};

Lightning.SendPayment = {
  methodName: "SendPayment",
  service: Lightning,
  requestStream: true,
  responseStream: true,
  requestType: rpc_pb.SendRequest,
  responseType: rpc_pb.SendResponse
};

Lightning.SendPaymentSync = {
  methodName: "SendPaymentSync",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.SendRequest,
  responseType: rpc_pb.SendResponse
};

Lightning.SendToRoute = {
  methodName: "SendToRoute",
  service: Lightning,
  requestStream: true,
  responseStream: true,
  requestType: rpc_pb.SendToRouteRequest,
  responseType: rpc_pb.SendResponse
};

Lightning.SendToRouteSync = {
  methodName: "SendToRouteSync",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.SendToRouteRequest,
  responseType: rpc_pb.SendResponse
};

Lightning.AddInvoice = {
  methodName: "AddInvoice",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.Invoice,
  responseType: rpc_pb.AddInvoiceResponse
};

Lightning.ListInvoices = {
  methodName: "ListInvoices",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ListInvoiceRequest,
  responseType: rpc_pb.ListInvoiceResponse
};

Lightning.LookupInvoice = {
  methodName: "LookupInvoice",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.PaymentHash,
  responseType: rpc_pb.Invoice
};

Lightning.SubscribeInvoices = {
  methodName: "SubscribeInvoices",
  service: Lightning,
  requestStream: false,
  responseStream: true,
  requestType: rpc_pb.InvoiceSubscription,
  responseType: rpc_pb.Invoice
};

Lightning.DecodePayReq = {
  methodName: "DecodePayReq",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.PayReqString,
  responseType: rpc_pb.PayReq
};

Lightning.ListPayments = {
  methodName: "ListPayments",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ListPaymentsRequest,
  responseType: rpc_pb.ListPaymentsResponse
};

Lightning.DeleteAllPayments = {
  methodName: "DeleteAllPayments",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.DeleteAllPaymentsRequest,
  responseType: rpc_pb.DeleteAllPaymentsResponse
};

Lightning.DescribeGraph = {
  methodName: "DescribeGraph",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ChannelGraphRequest,
  responseType: rpc_pb.ChannelGraph
};

Lightning.GetNodeMetrics = {
  methodName: "GetNodeMetrics",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.NodeMetricsRequest,
  responseType: rpc_pb.NodeMetricsResponse
};

Lightning.GetChanInfo = {
  methodName: "GetChanInfo",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ChanInfoRequest,
  responseType: rpc_pb.ChannelEdge
};

Lightning.GetNodeInfo = {
  methodName: "GetNodeInfo",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.NodeInfoRequest,
  responseType: rpc_pb.NodeInfo
};

Lightning.QueryRoutes = {
  methodName: "QueryRoutes",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.QueryRoutesRequest,
  responseType: rpc_pb.QueryRoutesResponse
};

Lightning.GetNetworkInfo = {
  methodName: "GetNetworkInfo",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.NetworkInfoRequest,
  responseType: rpc_pb.NetworkInfo
};

Lightning.StopDaemon = {
  methodName: "StopDaemon",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.StopRequest,
  responseType: rpc_pb.StopResponse
};

Lightning.SubscribeChannelGraph = {
  methodName: "SubscribeChannelGraph",
  service: Lightning,
  requestStream: false,
  responseStream: true,
  requestType: rpc_pb.GraphTopologySubscription,
  responseType: rpc_pb.GraphTopologyUpdate
};

Lightning.DebugLevel = {
  methodName: "DebugLevel",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.DebugLevelRequest,
  responseType: rpc_pb.DebugLevelResponse
};

Lightning.FeeReport = {
  methodName: "FeeReport",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.FeeReportRequest,
  responseType: rpc_pb.FeeReportResponse
};

Lightning.UpdateChannelPolicy = {
  methodName: "UpdateChannelPolicy",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.PolicyUpdateRequest,
  responseType: rpc_pb.PolicyUpdateResponse
};

Lightning.ForwardingHistory = {
  methodName: "ForwardingHistory",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ForwardingHistoryRequest,
  responseType: rpc_pb.ForwardingHistoryResponse
};

Lightning.ExportChannelBackup = {
  methodName: "ExportChannelBackup",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ExportChannelBackupRequest,
  responseType: rpc_pb.ChannelBackup
};

Lightning.ExportAllChannelBackups = {
  methodName: "ExportAllChannelBackups",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ChanBackupExportRequest,
  responseType: rpc_pb.ChanBackupSnapshot
};

Lightning.VerifyChanBackup = {
  methodName: "VerifyChanBackup",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ChanBackupSnapshot,
  responseType: rpc_pb.VerifyChanBackupResponse
};

Lightning.RestoreChannelBackups = {
  methodName: "RestoreChannelBackups",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.RestoreChanBackupRequest,
  responseType: rpc_pb.RestoreBackupResponse
};

Lightning.SubscribeChannelBackups = {
  methodName: "SubscribeChannelBackups",
  service: Lightning,
  requestStream: false,
  responseStream: true,
  requestType: rpc_pb.ChannelBackupSubscription,
  responseType: rpc_pb.ChanBackupSnapshot
};

Lightning.BakeMacaroon = {
  methodName: "BakeMacaroon",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.BakeMacaroonRequest,
  responseType: rpc_pb.BakeMacaroonResponse
};

Lightning.ListMacaroonIDs = {
  methodName: "ListMacaroonIDs",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ListMacaroonIDsRequest,
  responseType: rpc_pb.ListMacaroonIDsResponse
};

Lightning.DeleteMacaroonID = {
  methodName: "DeleteMacaroonID",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.DeleteMacaroonIDRequest,
  responseType: rpc_pb.DeleteMacaroonIDResponse
};

Lightning.ListPermissions = {
  methodName: "ListPermissions",
  service: Lightning,
  requestStream: false,
  responseStream: false,
  requestType: rpc_pb.ListPermissionsRequest,
  responseType: rpc_pb.ListPermissionsResponse
};

exports.Lightning = Lightning;

function LightningClient(serviceHost, options) {
  this.serviceHost = serviceHost;
  this.options = options || {};
}

LightningClient.prototype.walletBalance = function walletBalance(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.WalletBalance, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.channelBalance = function channelBalance(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ChannelBalance, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.getTransactions = function getTransactions(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.GetTransactions, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.estimateFee = function estimateFee(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.EstimateFee, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.sendCoins = function sendCoins(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.SendCoins, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.listUnspent = function listUnspent(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ListUnspent, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.subscribeTransactions = function subscribeTransactions(requestMessage, metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.invoke(Lightning.SubscribeTransactions, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onMessage: function (responseMessage) {
      listeners.data.forEach(function (handler) {
        handler(responseMessage);
      });
    },
    onEnd: function (status, statusMessage, trailers) {
      listeners.status.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners.end.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners = null;
    }
  });
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

LightningClient.prototype.sendMany = function sendMany(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.SendMany, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.newAddress = function newAddress(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.NewAddress, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.signMessage = function signMessage(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.SignMessage, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.verifyMessage = function verifyMessage(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.VerifyMessage, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.connectPeer = function connectPeer(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ConnectPeer, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.disconnectPeer = function disconnectPeer(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.DisconnectPeer, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.listPeers = function listPeers(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ListPeers, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.subscribePeerEvents = function subscribePeerEvents(requestMessage, metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.invoke(Lightning.SubscribePeerEvents, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onMessage: function (responseMessage) {
      listeners.data.forEach(function (handler) {
        handler(responseMessage);
      });
    },
    onEnd: function (status, statusMessage, trailers) {
      listeners.status.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners.end.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners = null;
    }
  });
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

LightningClient.prototype.getInfo = function getInfo(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.GetInfo, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.getRecoveryInfo = function getRecoveryInfo(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.GetRecoveryInfo, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.pendingChannels = function pendingChannels(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.PendingChannels, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.listChannels = function listChannels(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ListChannels, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.subscribeChannelEvents = function subscribeChannelEvents(requestMessage, metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.invoke(Lightning.SubscribeChannelEvents, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onMessage: function (responseMessage) {
      listeners.data.forEach(function (handler) {
        handler(responseMessage);
      });
    },
    onEnd: function (status, statusMessage, trailers) {
      listeners.status.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners.end.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners = null;
    }
  });
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

LightningClient.prototype.closedChannels = function closedChannels(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ClosedChannels, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.openChannelSync = function openChannelSync(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.OpenChannelSync, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.openChannel = function openChannel(requestMessage, metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.invoke(Lightning.OpenChannel, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onMessage: function (responseMessage) {
      listeners.data.forEach(function (handler) {
        handler(responseMessage);
      });
    },
    onEnd: function (status, statusMessage, trailers) {
      listeners.status.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners.end.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners = null;
    }
  });
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

LightningClient.prototype.fundingStateStep = function fundingStateStep(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.FundingStateStep, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.channelAcceptor = function channelAcceptor(metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.client(Lightning.ChannelAcceptor, {
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport
  });
  client.onEnd(function (status, statusMessage, trailers) {
    listeners.status.forEach(function (handler) {
      handler({ code: status, details: statusMessage, metadata: trailers });
    });
    listeners.end.forEach(function (handler) {
      handler({ code: status, details: statusMessage, metadata: trailers });
    });
    listeners = null;
  });
  client.onMessage(function (message) {
    listeners.data.forEach(function (handler) {
      handler(message);
    })
  });
  client.start(metadata);
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    write: function (requestMessage) {
      client.send(requestMessage);
      return this;
    },
    end: function () {
      client.finishSend();
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

LightningClient.prototype.closeChannel = function closeChannel(requestMessage, metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.invoke(Lightning.CloseChannel, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onMessage: function (responseMessage) {
      listeners.data.forEach(function (handler) {
        handler(responseMessage);
      });
    },
    onEnd: function (status, statusMessage, trailers) {
      listeners.status.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners.end.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners = null;
    }
  });
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

LightningClient.prototype.abandonChannel = function abandonChannel(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.AbandonChannel, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.sendPayment = function sendPayment(metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.client(Lightning.SendPayment, {
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport
  });
  client.onEnd(function (status, statusMessage, trailers) {
    listeners.status.forEach(function (handler) {
      handler({ code: status, details: statusMessage, metadata: trailers });
    });
    listeners.end.forEach(function (handler) {
      handler({ code: status, details: statusMessage, metadata: trailers });
    });
    listeners = null;
  });
  client.onMessage(function (message) {
    listeners.data.forEach(function (handler) {
      handler(message);
    })
  });
  client.start(metadata);
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    write: function (requestMessage) {
      client.send(requestMessage);
      return this;
    },
    end: function () {
      client.finishSend();
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

LightningClient.prototype.sendPaymentSync = function sendPaymentSync(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.SendPaymentSync, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.sendToRoute = function sendToRoute(metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.client(Lightning.SendToRoute, {
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport
  });
  client.onEnd(function (status, statusMessage, trailers) {
    listeners.status.forEach(function (handler) {
      handler({ code: status, details: statusMessage, metadata: trailers });
    });
    listeners.end.forEach(function (handler) {
      handler({ code: status, details: statusMessage, metadata: trailers });
    });
    listeners = null;
  });
  client.onMessage(function (message) {
    listeners.data.forEach(function (handler) {
      handler(message);
    })
  });
  client.start(metadata);
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    write: function (requestMessage) {
      client.send(requestMessage);
      return this;
    },
    end: function () {
      client.finishSend();
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

LightningClient.prototype.sendToRouteSync = function sendToRouteSync(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.SendToRouteSync, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.addInvoice = function addInvoice(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.AddInvoice, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.listInvoices = function listInvoices(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ListInvoices, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.lookupInvoice = function lookupInvoice(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.LookupInvoice, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.subscribeInvoices = function subscribeInvoices(requestMessage, metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.invoke(Lightning.SubscribeInvoices, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onMessage: function (responseMessage) {
      listeners.data.forEach(function (handler) {
        handler(responseMessage);
      });
    },
    onEnd: function (status, statusMessage, trailers) {
      listeners.status.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners.end.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners = null;
    }
  });
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

LightningClient.prototype.decodePayReq = function decodePayReq(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.DecodePayReq, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.listPayments = function listPayments(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ListPayments, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.deleteAllPayments = function deleteAllPayments(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.DeleteAllPayments, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.describeGraph = function describeGraph(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.DescribeGraph, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.getNodeMetrics = function getNodeMetrics(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.GetNodeMetrics, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.getChanInfo = function getChanInfo(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.GetChanInfo, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.getNodeInfo = function getNodeInfo(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.GetNodeInfo, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.queryRoutes = function queryRoutes(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.QueryRoutes, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.getNetworkInfo = function getNetworkInfo(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.GetNetworkInfo, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.stopDaemon = function stopDaemon(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.StopDaemon, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.subscribeChannelGraph = function subscribeChannelGraph(requestMessage, metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.invoke(Lightning.SubscribeChannelGraph, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onMessage: function (responseMessage) {
      listeners.data.forEach(function (handler) {
        handler(responseMessage);
      });
    },
    onEnd: function (status, statusMessage, trailers) {
      listeners.status.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners.end.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners = null;
    }
  });
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

LightningClient.prototype.debugLevel = function debugLevel(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.DebugLevel, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.feeReport = function feeReport(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.FeeReport, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.updateChannelPolicy = function updateChannelPolicy(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.UpdateChannelPolicy, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.forwardingHistory = function forwardingHistory(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ForwardingHistory, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.exportChannelBackup = function exportChannelBackup(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ExportChannelBackup, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.exportAllChannelBackups = function exportAllChannelBackups(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ExportAllChannelBackups, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.verifyChanBackup = function verifyChanBackup(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.VerifyChanBackup, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.restoreChannelBackups = function restoreChannelBackups(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.RestoreChannelBackups, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.subscribeChannelBackups = function subscribeChannelBackups(requestMessage, metadata) {
  var listeners = {
    data: [],
    end: [],
    status: []
  };
  var client = grpc.invoke(Lightning.SubscribeChannelBackups, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onMessage: function (responseMessage) {
      listeners.data.forEach(function (handler) {
        handler(responseMessage);
      });
    },
    onEnd: function (status, statusMessage, trailers) {
      listeners.status.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners.end.forEach(function (handler) {
        handler({ code: status, details: statusMessage, metadata: trailers });
      });
      listeners = null;
    }
  });
  return {
    on: function (type, handler) {
      listeners[type].push(handler);
      return this;
    },
    cancel: function () {
      listeners = null;
      client.close();
    }
  };
};

LightningClient.prototype.bakeMacaroon = function bakeMacaroon(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.BakeMacaroon, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.listMacaroonIDs = function listMacaroonIDs(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ListMacaroonIDs, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.deleteMacaroonID = function deleteMacaroonID(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.DeleteMacaroonID, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

LightningClient.prototype.listPermissions = function listPermissions(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(Lightning.ListPermissions, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

exports.LightningClient = LightningClient;

